resources:
- repo: self

trigger:
- master
- maint/*

phases:
- phase: linux_trusty_gcc_openssl
  displayName: 'Linux (Trusty; GCC; OpenSSL)'
  queue:
    name: 'Hosted Linux Preview'
  steps:
  - template: ci/vsts-docker.yml
    parameters:
      imageName: 'libgit2/trusty-openssl:latest'
      environmentVariables: |
       CC=gcc
       LEAK_CHECK=valgrind

- phase: linux_trusty_clang_openssl
  displayName: 'Linux (Trusty; Clang; OpenSSL)'
  queue:
    name: 'Hosted Linux Preview'
  steps:
  - template: ci/vsts-docker.yml
    parameters:
      imageName: 'libgit2/trusty-openssl:latest'
      environmentVariables: |
       CC=clang
       LEAK_CHECK=valgrind
      workDir: '/build'
      containerCommand: '/src/ci/test.sh'
      detached: false

- phase: macos
  displayName: 'macOS'
  queue:
    name: 'Hosted macOS Preview'
  steps:
  - bash: . '$(Build.SourcesDirectory)/ci/setup-osx.sh'
    displayName: Setup
  - template: ci/vsts-bash.yml
    parameters:
      environmentVariables:
        TMPDIR: $(Agent.TempDirectory)
        PKG_CONFIG_PATH: /usr/local/opt/openssl/lib/pkgconfig
        LEAK_CHECK: leaks

- phase: windows_vs_amd64
  displayName: 'Windows (Visual Studio; amd64)'
  queue:
    name: Hosted
  steps:
  - template: ci/vsts-powershell.yml
    parameters:
      environmentVariables:
        CMAKE_OPTIONS: -DMSVC_CRTDBG=ON -G"Visual Studio 12 2013 Win64"

- phase: windows_vs_x86
  displayName: 'Windows (Visual Studio; x86)'
  queue:
    name: Hosted
  steps:
  - template: ci/vsts-powershell.yml
    parameters:
      environmentVariables:
        CMAKE_OPTIONS: -DMSVC_CRTDBG=ON -G"Visual Studio 12 2013"

- phase: windows_mingw_amd64
  displayName: 'Windows (MinGW; amd64)'
  queue:
    name: Hosted
  steps:
  - powershell: . '$(Build.SourcesDirectory)\ci\setup-mingw.ps1'
    displayName: Setup
    env:
      TEMP: $(Agent.TempDirectory)
      ARCH: amd64
  - template: ci/vsts-powershell.yml
    parameters:
      environmentVariables:
        CMAKE_OPTIONS: -G"MinGW Makefiles"
        PATH: $(Agent.TempDirectory)\mingw64\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\CMake\bin

- phase: windows_mingw_x86
  displayName: 'Windows (MinGW; x86)'
  queue:
    name: Hosted
  steps:
  - powershell: . '$(Build.SourcesDirectory)\ci\setup-mingw.ps1'
    displayName: Setup
    workingDirectory: '$(Build.BinariesDirectory)'
    env:
      TEMP: $(Agent.TempDirectory)
      ARCH: x86
  - template: ci/vsts-powershell.yml
    parameters:
      environmentVariables:
        CMAKE_OPTIONS: -G"MinGW Makefiles"
        PATH: $(Agent.TempDirectory)\mingw32\bin;C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\CMake\bin
